name: migraphx

on: [push, pull_request]

jobs:
  cancel:
    runs-on: ubuntu-latest
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.6.0
        with:
          access_token: ${{ github.token }}
  tidy:
    runs-on: ubuntu-18.04

    steps:
    - name: Setup tmate session
      uses: mxschmitt/action-tmate@v3
